/*
 * Copyright(c) 2024-2026 China Telecom Cloud Technologies Co., Ltd. All rights
 * reserved. ctscat is licensed under Mulan PSL v2. You can use this software
 * according to the terms and conditions of the Mulan PSL V2. You may obtain a
 * copy of Mulan PSL v2 at: http://license.coscl.org.cn/MulanPSL2.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.  See the Mulan PSL v2 for
 * more details.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
//!
//! DEPRECATED: This entity is kept for backward compatibility only.
//! Use l1_commit_records instead.

use sea_orm::{entity::prelude::*, JsonValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commit_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tracking_id: i32,
    pub commit_sha: String,
    #[sea_orm(column_type = "Text")]
    pub commit_message: String,
    pub author_name: String,
    pub author_email: String,
    pub committed_at: DateTimeUtc,
    pub change_type: Option<String>,
    pub primary_change_type: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub cve_list: Option<JsonValue>,
    pub spec_changed: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub patch_stats: Option<JsonValue>,
