/*
 * Copyright(c) 2024-2026 China Telecom Cloud Technologies Co., Ltd. All rights
 * reserved. ctscat is licensed under Mulan PSL v2. You can use this software
 * according to the terms and conditions of the Mulan PSL V2. You may obtain a
 * copy of Mulan PSL v2 at: http://license.coscl.org.cn/MulanPSL2.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.  See the Mulan PSL v2 for
 * more details.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "spec_snapshots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub commit_record_id: i32,
    pub spec_filename: String,
    pub name: String,
    pub version: String,
    pub release: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub license: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub sources: String,
    #[sea_orm(column_type = "Text")]
    pub patches: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub latest_changelog_entry: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub full_content: String,
    pub content_hash: String,
    #[sea_orm(column_type = "Text")]
    pub download_url: String,
    pub fetched_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::l1_commit_records::Entity",
        from = "Column::CommitRecordId",
        to = "super::l1_commit_records::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommitRecords,
}

impl Related<super::l1_commit_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
