/*
 * Copyright(c) 2024-2026 China Telecom Cloud Technologies Co., Ltd. All rights
 * reserved. ctscat is licensed under Mulan PSL v2. You can use this software
 * according to the terms and conditions of the Mulan PSL V2. You may obtain a
 * copy of Mulan PSL v2 at: http://license.coscl.org.cn/MulanPSL2.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.  See the Mulan PSL v2 for
 * more details.
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tracking")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub package_id: i32,
    pub distro_id: i32,
    pub l1_branch: String,
    pub l1_repo_owner: String,
    pub l1_repo_name: String,
    pub l2_branch: String,
    pub l2_repo_path: String,
    pub tracking_status: String,
    pub last_sync_time: Option<DateTimeUtc>,
    pub last_l1_commit_sha: Option<String>,
    pub last_l2_commit_sha: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::l1_commit_records::Entity")]
    CommitRecords,
    #[sea_orm(has_many = "super::issues::Entity")]
    Issues,
    #[sea_orm(has_many = "super::tracking_reports::Entity")]
    TrackingReports,
    #[sea_orm(has_many = "super::sync_jobs::Entity")]
    SyncJobs,
    #[sea_orm(has_many = "super::l2_snapshots::Entity")]
    L2Snapshots,
    #[sea_orm(
        belongs_to = "super::distros::Entity",
        from = "Column::DistroId",
        to = "super::distros::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Distros,
    #[sea_orm(
        belongs_to = "super::packages::Entity",
        from = "Column::PackageId",
        to = "super::packages::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Packages,
}

impl Related<super::l1_commit_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitRecords.def()
    }
}

